module.exports = {
  SHINOBIAPIURL: 'THE API ENDPOINT FOR YOUR SHINOBI INSTANCE e.g. http://192.168.1.2:8080',
  APIKEY: 'YOURSHINOBIAPIKEY',
  GROUPKEY: 'YOURSHINOBIGROUPKEY',
  SERVER_PORT: 2525,
  SERVER_HOST: false,
  SMTP_USER: 'bert',
  SMTP_PASS: 'ernie'
}
